# Generated by Django 5.0.6 on 2024-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
