# Generated by Django 5.0.6 on 2024-05-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprocessingstatus',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='videoprocessingstatus',
            name='progress',
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
